### ISSUE TITLE
Complete Meetup integration

### ISSUE THREAD

**Issue by tommerty** [tommerty/Dublin-Linux-Org#2]
On the homepage there's currently space to add a section to embed a meetup link.

Here's what I found online: https://asp.net-hacker.rocks/2017/03/13/integrate-meetup-events-on-your-website.html

**Comment by Mikee-3000** [comment]
So i added it in the meetup-event branch. Let me know what else it needs, what i did is fairly rudimentary.

**Comment by tommerty** [comment]
Linked the branch to the PR now. I got some styling in place, maybe just some finer adjustments to the time formatting, and then I think it looks good if you do
